README.md, src/App.xaml.cs, src/Captura.csproj, src/MainWindow.xaml, src/MixedAudioProvider.cs, src/ViewModels/AudioViewModel.cs, src/ViewModels/MainViewModel.cs, src/Views/AudioView.xaml, src/packages.config
Adds the ability to record Microphone input and Speaker Output (Loopback) simultaneously.
Uses [ManagedBass](https://github.com/ManagedBass/ManagedBass) instead of [NAudio](https://github.com/NAudio/NAudio).
Sepearate boxes are provided for selection of Microphone and Loopback device.
=> Recording both Microphone and Loopback

src/Captura.Core/Models/VideoItems/VideoSourceKind.cs, src/Captura.Core/Models/VideoWriterItems/VideoWriterKind.cs, src/Captura.Core/Services/ServiceName.cs, src/Captura.Core/Settings.cs, src/Captura.Core/ViewModels/MainViewModel.cs, src/Captura/MainWindow.xaml.cs, src/Captura/Presentation/Controls/RegionSelector.xaml.cs
=> Remember Sources, Codecs and Window Location

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Models/FFMpeg/FFMpegAudioWriter.cs, src/Captura.Core/Models/FFMpeg/FFMpegMuxedWriter.cs, src/Captura.Core/Models/FFMpeg/FFMpegVideoWriter.cs, src/Captura.Core/Models/SystemTrayManager.cs, src/Captura.Core/Services/ServiceProvider.cs, src/Captura.Core/Settings.cs, src/Captura.Core/ViewModels/MainViewModel.cs, src/Captura.Core/ViewModels/Properties.cs, src/Captura.Core/ViewModels/RecentItemViewModel.cs, src/Captura/MainWindow.xaml, src/Captura/MainWindow.xaml.cs, src/Captura/Presentation/Controls/NumericBox.xaml.cs, src/Captura/Presentation/Controls/RecentItem.xaml, src/Captura/Presentation/Controls/ScreenShotBalloon.xaml, src/Captura/Presentation/Controls/ScreenShotBalloon.xaml.cs, src/Captura/ViewModels/WebCamViewModel.cs, src/Captura/Views/ConfigView.xaml
- Added Message Boxes for showing Errors with Stack Trace.
- **fix:** Cache Images in `ScreenShotBalloon`. Fixes the unability to delete files.
- Unconstrained Gif renamed to Variable Frame Rate.
- Confirm RecentItem deletion.
- Added `ServiceProvider.LaunchFile` to handle errors in opening files.
- Removed `SystemTrayManager`.
- Hides FFMpeg banner.
- **fix:** After recording tasks can run before saving is completed.
- Asks before Exit during Recording.
- **fix:** Hide Keystrokes and Clicks capture buttons when `MouseKeyHook` library is not present.
=> Fixes and Improvement

src/Captura/Captura.UI.csproj, src/Captura/Models/Dpi.cs, src/Captura/Presentation/Controls/RegionSelector.xaml.cs
=> Fix Region Selection on High DPI

src/Captura.Core/Properties/Resources.Designer.cs, src/Captura.Core/Properties/Resources.resx, src/Captura/Captura.UI.csproj, src/Captura/MainWindow.xaml, src/Captura/Views/AboutView.xaml, src/Captura/Views/AboutView.xaml.cs, src/Captura/Views/ConfigView.xaml, src/Captura/Views/ConfigView.xaml.cs, src/Captura/Views/ExtrasView.xaml, src/Captura/Views/ExtrasView.xaml.cs, src/Captura/Views/FFMpegView.xaml, src/Captura/Views/FFMpegView.xaml.cs, src/Captura/Views/HotkeyView.xaml, src/Captura/Views/HotkeyView.xaml.cs, src/UITests/ScreenShots.cs
Vertical Tabs under the **Configure** tab:
- **Options:** The original content of Configure tab.
- **Hotkeys:** Hotkeys tab moved here
- **FFMpeg:** FFMpeg log and folder
- **Extras:** The content of Extras window.
=> Tabbed Config page

appveyor.yml, appveyor/Choco.ps1, appveyor/Pack-Release.ps1, appveyor/Update-Version.ps1
=> Allow Prerelease Tags on Appveyor

src/Captura.Console/Program.cs
=> Handling Redirected Input in Captura.Console

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.es-AR.resx, src/Captura.Core/Properties/Resources.resx
**Mathew**,
Hi! Here's the _Español (Argentina) [Spanish (Argentina)]_ locale.
I can't tell if they are big differences with the _Español (México)_ locale since I'm not able to make it work. :sob:
Kind regards.
=> es-AR locale

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.ru.resx
Add russian language resource file
=> Add russian language resource file

src/Captura.Core/Models/DeskDuplImageProvider.cs, src/Captura.Core/Models/VideoItems/FullScreenItem.cs, src/Captura.Core/Models/VideoItems/ScreenItem.cs, src/DesktopDuplication/DesktopDuplicator.cs
=> Fix Screen recording with Desktop Duplication

src/Captura.Core/Properties/Resources.it.resx
As title, contributing to #108
=> Added Italian Translation

src/Captura.Core/Properties/Resources.de.resx
=> Added german translation

src/Captura.Core/Resources.id.resx
Issue https://github.com/MathewSachin/Captura/issues/108
=> Added Indonesian Translation

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.ua.resx
Issue #108. Please review
Thank you in advance
=> Added Ukrainian Translation 

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.he.resx
Hope it helps :)
Happy Hacktoberfest!
( Edit: i'll reference the #108 for this to show there)
=> Added Hebrew translation

src/Captura.Core/Properties/Resources.pt.resx
Corrected grammatical errors :)
=> Update PT translation

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.sv.resx
Added Swedish translation
Happy Hacktoberfest! :)
=> Added Swedish Translation

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.ar.resx
Arabic translation added, following Microsoft's standard terminology
=> Arabic translation added

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.pl.resx
Once again, now properly rebased on master :)
#108
=> Added Polish translation

src/Captura.Core/Properties/Resources.fr.resx, src/Captura.Core/Properties/Resources.resx
=> adds French translation

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.da.resx
=> Add Danish translation

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.is.resx
=> Added an Icelandic translation of Captura

src/Captura.Core/Captura.Core.csproj, src/Captura.Core/Properties/Resources.no.resx
=> Add Norwegian translation

src/Captura.Core/Properties/Resources.ro.resx
=> Added Romanian translation

src/Captura/MainWindow.xaml.cs
=> Replace MainWindow if outside desktop rectangle at startup.

src/Captura.Core/Models/MouseKeyHook/MouseKeyHook.cs, src/Captura.Core/Settings/Models/MouseClickSettings.cs, src/Captura.Core/Settings/Models/TextOverlaySettings.cs, src/Captura/Views/OverlaysView.xaml
=> Separate Colors for Right and Middle click overlays

src/Captura.Core/ViewModels/MainViewModel.cs, src/Captura/Captura.csproj, src/Captura/Models/MainModule.cs, src/Captura/Models/PreviewWriter.cs, src/Captura/Models/PreviewWriterItem.cs, src/Captura/Models/PreviewWriterProvider.cs, src/Captura/Views/PreviewWindow.xaml, src/Captura/Views/PreviewWindow.xaml.cs, src/Screna/Recorder/VFRGifRecorder.cs
Preview Window as a new video output type.
=> Preview Window

src/Captura.Core/Models/AudioSourceItems/AudioSource.cs, src/Captura.Core/Models/AudioSourceItems/BassAudioSource.cs, src/Captura.Core/Models/AudioSourceItems/BassItem.cs, src/Captura.Core/Models/MixedAudioProvider.cs, src/Captura.Core/Settings/Models/AudioSettings.cs, src/Captura.Core/ViewModels/MainViewModel.cs, src/Captura/Views/MainView.xaml
- A new checkbox is added to specify whether to record Audio or not.
- When audio recording is enabled, check-boxes are available next to every audio source which can be toggled during recording to include or exclude the audio device.
=> Change Audio sources during recording

src/Captura/Views/OverlayWindow.xaml, src/Captura/Views/OverlayWindow.xaml.cs
In Overlay Window Preview, Mouse click and Mouse Pointer overlays can be previewed.
=> Mouse Overlay Preview

src/Captura.Console/Program.cs, src/Captura.Core/Captura.Core.csproj, src/Captura.Core/CoreModule.cs, src/Captura.Core/Models/CensorOverlay.cs, src/Captura.Core/Settings/Models/CensorOverlaySettings.cs, src/Captura.Core/Settings/Settings.cs, src/Captura.Core/ViewModels/CensorOverlaysViewModel.cs, src/Captura.Core/ViewModels/CustomImageOverlaysViewModel.cs, src/Captura.Core/ViewModels/CustomOverlaysViewModel.cs, src/Captura.Core/ViewModels/MainViewModel.cs, src/Captura.Core/ViewModels/OverlayListViewModel.cs, src/Captura.Core/ViewModels/Properties.cs, src/Captura/Views/OverlayWindow.xaml, src/Captura/Views/OverlayWindow.xaml.cs
=> Implemented Censor Overlay

appveyor.yml, build.cake, src/Captura.Console/Properties/AssemblyInfo.cs, src/Captura/Properties/AssemblyInfo.cs
Dev build versions were causing confusion for users. So, a separate versioning scheme will be followed for them.
=> Dev Builds versioned as 0.0.[BUILD NO]

src/Captura.Console/Program.cs, src/Captura.Core/Fakes/FakeVideoSourcePicker.cs, src/Captura.Core/Fakes/FakesModule.cs
=> Cmdline Window, Screen capture fix

src/Captura.Base/Captura.Base.csproj, src/Captura.Bass/Captura.Bass.csproj, src/Captura.Console/Captura.Console.csproj, src/Captura.Core/Captura.Core.csproj, src/Captura.FFmpeg/Captura.FFmpeg.csproj, src/Captura.Fakes/Captura.Fakes.csproj, src/Captura.Hotkeys/Captura.Hotkeys.csproj, src/Captura.Loc/Captura.Loc.csproj, src/Captura.MouseKeyHook/Captura.MouseKeyHook.csproj, src/Captura.NAudio/Captura.NAudio.csproj, src/Captura.Native/Captura.Native.csproj, src/Captura.SharpAvi/Captura.SharpAvi.csproj, src/Captura.Webcam/Captura.Webcam.csproj, src/Captura/Captura.csproj, src/DesktopDuplication/DesktopDuplication.csproj, src/Screna/Screna.csproj
UI, Console and Test projects were not migrated.
=> Migrate to new csproj format

src/Captura.Core/CoreModule.cs, src/Captura.Core/Models/AroundMouseItem.cs, src/Captura.Core/Models/AroundMouseSourceProvider.cs, src/Captura.Core/Settings/Settings.cs, src/Captura.Core/ViewModels/ScreenShotModel.cs, src/Captura.ViewCore/ViewModels/ViewConditionsModel.cs, src/Captura/Pages/HomePage.xaml, src/Screna/ImageProviders/AroundMouseImageProvider.cs
A new mode for recording the region around mouse cursor.
=> Around Mouse Recording

src/Screna/VideoSourceProviders/WindowSourceProvider.cs
=> Fix: Negative Window handles not supported by CLI

src/Captura.ViewCore/ViewModels/VideoSourcesViewModel.cs, src/Captura/Captura.csproj, src/Captura/Controls/VideoSourceKindList.xaml, src/Captura/Models/VideoSourcePicker.cs, src/Captura/ViewModels/ScreenPickerViewModel.cs, src/Captura/Windows/ScreenPickerWindow.xaml, src/Captura/Windows/ScreenPickerWindow.xaml.cs
Shows a dialog box with previews and names of screens instead of a fullscreen selector
=> Screen picker dialog

docs/Acknowledgements.md
Hi, I'm a [Korean translator](https://github.com/MathewSachin/Captura/pull/366#issuecomment-468089427) of Captura.
I found a small typo in a document, fixed it!
=> Fix typo in Acknowledgements.md

src/Captura.Core/Settings/Settings.cs, src/Captura.ViewCore/HotkeyActor.cs, src/Captura/Pages/HotkeysPage.xaml
=> Auto start recording option for Region picker hotkey
