MathewSachin/Captura

- src/Captura.Core/Captura.Core.csproj
- src/Captura.Core/Models/IRegionProvider.cs
- src/Captura.Core/Models/ISystemTray.cs
- src/Captura.Core/Models/SystemTrayManager.cs
- src/Captura.Core/Services/ServiceName.cs
- src/Captura.Core/ViewModels/MainViewModel.cs
- src/Captura.Core/ViewModels/Properties.cs
- src/Captura.Core/ViewModels/VideoViewModel.cs
- src/Captura/Captura.csproj
- src/Captura/MainWindow.xaml
- src/Captura/MainWindow.xaml.cs
- src/Captura/Models/RegionProvider.cs
- src/Captura/Models/SystemTray.cs
- src/Captura/Presentation/Controls/ScreenShotBalloon.xaml
- src/Captura/Presentation/Controls/ScreenShotBalloon.xaml.cs
- src/Captura/Presentation/Controls/TextBalloon.xaml
- src/Captura/Presentation/Controls/TextBalloon.xaml.cs
- src/Captura/packages.config
- Icons in context menu
- Data Binding
- Handled in View part
- Double click tray icon to show/hide MainWindow
- Improved Notifications.
- Removed Exit, Focus servies.
- IRegionProvider replaces the 4 Region services.
- ISystemTray replaces SystemTrayManager.
> Improve the System Tray

- appveyor.yml
- appveyor/Choco.ps1
- appveyor/Install.ps1
- appveyor/Pack-Release.ps1
- appveyor/Update-Version.ps1
- Scripts in `appveyor` folder.
- Tag format is enforced.
- For tag builds, version is determined from tag.
> Organize Appveyor scripts

- README.md
Hi,
I have updated Build Notes to add compilation steps using VS2015 and have successfully tested it.
> Update Build Notes. Add Steps for compilation via VS2015

- licenses/Ooki.Dialogs.txt
- src/Captura.Core/Captura.Core.csproj
- src/Captura.Core/ViewModels/Properties.cs
- src/Captura.Core/packages.config
VistaFolderBrowserDialog is better alternative of FolderBrowserDialog.
It has many enhancements.
It will automatically fall back to legacy FolderBrowserDialog on unsupported windows (e.g. WIndows XP).
**References:**
- https://mking.io/blog/a-better-alternative-to-the-winforms-folderbrowserdialog-using-ookii-dialogs
- http://www.ookii.org/software/dialogs/
> Use VistaFolderBrowserDialog instead of FolderBrowserDialog

- src/Captura.Console/Captura.Console.csproj
- src/Captura.Console/CmdOptions/FFMpegCmdOptions.cs
- src/Captura.Console/CmdOptions/VerbCmdOptions.cs
- src/Captura.Console/Program.cs
- src/Captura.Core/ViewModels/FFMpgDownloadViewModel.cs
Can now call captura ffmpeg --install [path] and ffmpeg will be installed to the specified location.
This uses the code already in the FFMpgDownloadViewModel.cs but calls it synchronously from the command-line.
As I imagine CLI use is primarily for scripted use then I can't see this being a problem but could be re-factored to run asynchronously and give CLI feedback of download progress if required (although it's still only 15Mb so should be quick for anyone).
> CLI FFMpeg Install

- src/Captura.Base/Audio/AudioSource.cs
- src/Captura.Base/Settings/AudioSettings.cs
- src/Captura.Bass/BassAudioProvider.cs
- src/Captura.Bass/BassAudioSource.cs
- src/Captura.Bass/Captura.Bass.csproj
- src/Captura.Core/Models/NoAudioSource.cs
- src/Captura.Core/ViewModels/RecordingViewModel.cs
- src/Captura/Pages/ExtrasPage.xaml
- src/Captura/Pages/MainPage.xaml
Related to #234 
Can be enabled at `Config / Extras`.
Audio Sources cannot be changed during recording if this option is enabled.
Playback Recorded audio in real-time option does not work with this option.
Files are named as `[FILE NAME].[INDEX].[EXTENSION]`. Index starts from 0.
Only the first file is added to the recent list.
Audio files are not added to recent list.
Audio files are in Wave format (`.wav`).
---
Changed Webcam separate file naming to `.webcam` from `-webcam` for consistency.
> Option to create Separate file for every Audio Source

- src/Captura.Core/Settings/Models/VisualSettings.cs
- src/Captura/Captura.csproj
- src/Captura/ValueConverters/IsLessThanConverter.cs
- src/Captura/ValueConverters/ValueConverters.xaml
- src/Captura/Windows/RegionSelector.xaml
- src/Captura/Windows/RegionSelector.xaml.cs
Implementing a thinner Region Selector.
Lots of work to do!
> Thin Region Selector

- src/Captura.Core/Settings/Settings.cs
- src/Captura.Core/ViewModels/RecordingViewModel.cs
- src/Captura/App.xaml
- src/Captura/Pages/ConfigPage.xaml
- src/Captura/ValueConverters/IsLessThanConverter.cs
- src/Captura/ValueConverters/NegatingConverter.cs
- src/Captura/Windows/MainWindow.xaml
- src/Captura/Windows/RegionSelector.xaml
Changing the `Start Delay (milliseconds)` option to `Pre-Start Countdown` which is specified in `seconds`.
Animated Countdown is displayed before recording in place of duration.
> Pre-Start Countdown

- src/Screna/VideoItems/FullScreenItem.cs
When capturing with multiple monitors mouse click overlay positions are not correct.
We need to transform the FullScreenItems like cursor position.
I have added two recordings showing the results before and after this fix.
[Captura.zip](https://github.com/MathewSachin/Captura/files/2460271/Captura.zip)
> Fix coordinate transform for full screen items

- src/Captura.Core/Settings/Models/VisualSettings.cs
- src/Captura.Core/ViewModels/MainViewModel.cs
- src/Captura.Hotkeys/HotKeyManager.cs
- src/Captura.Loc/LanguageFields.cs
- src/Captura.Loc/Languages/en.json
- src/Captura/Captura.csproj
- src/Captura/Pages/ConfigPage.xaml
- src/Captura/Pages/ConfigPage.xaml.cs
- src/Captura/Windows/MainWindow.xaml
- src/Captura/Windows/MainWindow.xaml.cs
- src/Captura/Windows/TrayConfigWindow.xaml
- src/Captura/Windows/TrayConfigWindow.xaml.cs
- Added a new window for configuring system tray icon and moved relevant settings there.
- Added a `Show Main Window` action in tray context menu.
- Left click action for the tray icon can be customised the same way as Hotkeys. It is set by default to `Show Main Window`.
Related to #299
> Customizable Tray Left Click Action

- .gitignore
- licenses/BASS.txt
- licenses/NAudio.txt
- src/Captura.Base/Audio/AudioSource.cs
- src/Captura.Base/Settings/AudioSettings.cs
- src/Captura.Bass/BassAudioSource.cs
- src/Captura.Bass/MixedAudioProvider.cs
- src/Captura.Core/Captura.Core.csproj
- src/Captura.Core/CoreModule.cs
- src/Captura.Core/Models/NoAudioSource.cs
- src/Captura.Core/ViewModels/MainViewModel.cs
- src/Captura.Core/ViewModels/RecordingViewModel.cs
- src/Captura.Loc/LanguageFields.cs
- src/Captura.Loc/Languages/en.json
- src/Captura.NAudio/Captura.NAudio.csproj
- src/Captura.NAudio/MixedAudioProvider.cs
- src/Captura.NAudio/NAudioItem.cs
- src/Captura.NAudio/NAudioProvider.cs
- src/Captura.NAudio/NAudioSource.cs
- src/Captura.NAudio/WasapiCaptureProvider.cs
- src/Captura.NAudio/WasapiLoopbackCaptureProvider.cs
- src/Captura.sln
- src/Captura/Pages/AudioPage.xaml
Fallback to NAudio when BASS is not available.
For testing, delete `bass.dll` or `bassmix.dll`.
Error message if BASS not present has been removed.
The currently used audio library is displayed in the UI.
The audio device must support WASAPI Shared mode in 32-bit floating-point, 44100 Hz, Stereo.
Recording to separate audio files is working.
Audio mixing works but changing sources during recording is not supported.
Removed `Playback recorded audio in real-time` option.
Requested in #323.
> NAudio support

- src/Captura.Base/Services/ServiceProvider.cs
- src/Captura.Console/Program.cs
- src/Captura.Core/Settings/Settings.cs
- src/Captura.Core/ViewModels/MainModel.cs
- src/Captura.FFmpeg/FFmpegService.cs
- src/Captura.FFmpeg/FFmpgDownloadViewModel.cs
- src/Captura.FFmpeg/Settings/FFMpegSettings.cs
- src/Captura.ViewCore/ViewModels/MainViewModel.cs
- src/Captura/Properties/AssemblyInfo.cs
- src/Captura/Windows/FFmpegDownloaderWindow.xaml
- src/Tests/Fixtures/AppRunnerFixture.cs
- src/Tests/Fixtures/TestManagerFixture.cs
`%CAPTURA_PATH%` will be recognized as app directory for the following:
> Support %CAPTURA_PATH%

- src/Captura.Base/Images/IEditableFrame.cs
- src/Captura.Base/Images/IFont.cs
- src/Captura.Base/Images/RepeatFrame.cs
- src/Captura.Base/Settings/TextOverlaySettings.cs
- src/Captura.MouseKeyHook/MouseKeyHook.cs
- src/Captura.Windows/Imaging/DrawingFont.cs
- src/Captura.Windows/Imaging/GraphicsEditor.cs
- src/Captura/Captura.csproj
- src/Captura/Controls/FontSelector.xaml
- src/Captura/Controls/FontSelector.xaml.cs
- src/Captura/Controls/TextOverlaySettingsControl.xaml
- src/Captura/Windows/OverlayWindow.xaml
- src/Captura/Windows/OverlayWindow.xaml.cs
- src/DesktopDuplication/Direct2DEditor.cs
- src/DesktopDuplication/Direct2DFont.cs
- src/Screna/Overlays/TextOverlay.cs
Requested in #363.
Default font is **Arial**.
> Font setting for Overlays

- src/Captura.Console/ConsoleManager.cs
- src/Captura.Console/Properties/launchSettings.json
- src/Captura.FFmpeg/FFMpegLogItem.cs
- src/Captura.FFmpeg/FFmpegModule.cs
- src/Captura.FFmpeg/FFmpegService.cs
- src/Captura.FFmpeg/IFFmpegLogEntry.cs
- src/Captura.FFmpeg/IFFmpegLogRepository.cs
- src/Captura.FFmpeg/Video/FFmpegRollingWriter.cs
- src/Captura.FFmpeg/Video/FFmpegRollingWriterItem.cs
- src/Captura.Fakes/FakeFFmpegLogRepository.cs
- src/Captura.Fakes/FakesModule.cs
- src/Captura.ViewCore/FFmpegLog.cs
- src/Captura.ViewCore/ViewCoreModule.cs
Requested in #182 
Capture last N seconds mode added for Console.
This feature will **NOT** be implemented for the UI version due to the involved complications.
Implemented as a new encoder: `roll:<duration>` where duration is specified in seconds.
```
captura-cli start --encoder roll:60
```
Separate file for webcam and separate audio files for every source may not work as intended in this mode.
Added `IFFmpegLogRepository` and a Fake implementation which is now used for Console version since lots of logs are being created in this mode.
> Rolling Recording (Capture last N seconds)

- src/Captura.Base/Images/IBitmapFrame.cs
- src/Captura.Base/Images/IFrameWrapper.cs
- src/Captura.Base/Images/IImageProvider.cs
- src/Captura.Base/Images/RepeatFrame.cs
- src/Captura.Core/CoreModule.cs
- src/Captura.Core/Settings/Models/VideoSettings.cs
- src/Captura.Core/WebcamImageProvider.cs
- src/Captura.Windows/Capture/RegionProvider.cs
- src/Captura.Windows/Capture/WindowProvider.cs
- src/Captura.Windows/Imaging/DrawingFrameBase.cs
- src/Captura.Windows/Native/Kernel32.cs
- src/Captura/Pages/VideoEncoderPage.xaml
- src/DesktopDuplication/DeskDuplImageProvider.cs
- src/DesktopDuplication/DesktopDuplication.csproj
- src/DesktopDuplication/Direct2DEditor.cs
- src/DesktopDuplication/MediaFoundation/MfItem.cs
- src/DesktopDuplication/MediaFoundation/MfManager.cs
- src/DesktopDuplication/MediaFoundation/MfWriter.cs
- src/DesktopDuplication/MediaFoundation/MfWriterProvider.cs
- src/DesktopDuplication/MediaFoundation/PackedLong.cs
- src/DesktopDuplication/MediaFoundation/RateControlMode.cs
- src/DesktopDuplication/Texture2DFrame.cs
- src/Screna/ImageProviders/OverlayedImageProvider.cs
- src/Screna/MultiDisposeFrame.cs
Using `MediaFoundation` `SinkWriter` considerably reduces CPU usage.
- Media Foundation made default writer.
- Works best with `Desktop Duplication`.
- Added `IBitmapFrame.CopyTo` overload accepting `IntPtr`.
- Added `IFrameWrapper` interface. This is implemented by `MultiDisposeFrame`.
- Added `IImageProvider.EditorType`.
> MediaFoundation SinkWriter

- README.md
- src/Captura.Console/App.config
- src/Captura.Console/Captura.Console.csproj
- src/Captura.Core/Captura.Core.csproj
- src/Captura.Hotkeys/Captura.Hotkeys.csproj
- src/Captura.MouseKeyHook/Captura.MouseKeyHook.csproj
- src/Captura.NAudio/Captura.NAudio.csproj
- src/Captura.SharpAvi/Captura.SharpAvi.csproj
- src/Captura.ViewCore/Captura.ViewCore.csproj
- src/Captura.Windows/Captura.Windows.csproj
- src/Captura/Captura.csproj
- src/Captura/app.config
- src/Tests/Tests.csproj
Moving to .Net 4.7.1 or above reduces the number of dependency DLLs which need to be distributed with Captura.
.Net 4.7.2 is available for Windows 7 SP1, Windows 8.1 and Windows 10 Anniversary update and above so that might not be a problem.
Number of dlls depended on by Captura is reduced by approx. 100 and 4 MB space is saved!
In addition, this pull-request remove dependencies on `Xceed.Wpf.AvalonDock` and `Xceed.Wpf.DataGrid` which saves another 5 libraries and 2.75 MB.
The only problem I could see with this is that Windows 10 users (who are still on Anniversary or Creators update) who could just download and run the earlier versions would now be prompted to install .Net 4.7.2.
> Move to .Net 4.7.2

- src/Captura/Presentation/PuncturedRect.cs
According to PVS-Studio, there is a potential error related to dependency property registration.
see https://www.viva64.com/en/w/v3047
> Fix dependency properties registration

- src/Captura.Console/Captura.Console.csproj
- src/Captura/Captura.csproj
- src/Tests/Tests.csproj
This is much simpler now that we don't reference BASS which required separate DLLs for x86 and x64 versions.
> Run as 64-bit on 64-bit system

- src/Captura/App.xaml.cs
- src/Captura/Captura.csproj
- src/Captura/Models/SingleInstanceManager.cs
- src/Captura/Windows/MainWindow.xaml.cs
If you start the app again, the app won't launch again, the already running instance gains focus.
A `Mutex` is used to ensure that only a single instance runs, and an `EventWaitHandle` is used to wake the single instance when you try to launch another.
> Single Instance

- src/Captura.MouseKeyHook/KeyOverlay.cs
- src/Captura.MouseKeyHook/KeyRecord/RepeatKeyRecord.cs
- src/Captura.MouseKeyHook/Models/KeystrokesSettings.cs
- src/Captura/Pages/KeystrokesPage.xaml
Requested in #485 
On the keystroke settings page, a checkbox has been added which can be unchecked to disable repeated key presses shown like `Ctrl x3`.
> Show repeat counter setting
